# Generated by Django 4.2.7 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_application_jamb_number_application_jamb_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code (e.g., ND-CHEW)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('nd', 'National Diploma'), ('dip', 'Diploma'), ('cert', 'Certificate'), ('retraining', 'Retraining')], default='dip', max_length=20)),
                ('duration', models.CharField(blank=True, default='2 Years', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True, help_text='Entry requirements for this programme')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accreditation_body', models.CharField(blank=True, help_text='e.g., CHPRBN, WAHEB', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-heartbeat)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('jamb', 'With JAMB'), ('non_jamb', 'Without JAMB')], default='jamb', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_choice',
            field=models.CharField(blank=True, choices=[('nd_chew', 'National Diploma in Community Health (ND CHEW)'), ('dip_env_health', 'Diploma in Environmental Health'), ('dip_him', 'Diploma in Health Information Management'), ('dip_xray', 'Diploma in X-Ray and Imaging Technology'), ('dip_nutrition', 'Diploma in Nutrition and Dietetics'), ('cert_jchew', 'Certificate in Community Health (JCHEW)'), ('retraining_jchew', 'Retraining Programme in Community Health'), ('dip_pharmacy', 'Diploma in Pharmacy Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('nd_chew', 'National Diploma in Community Health (ND CHEW)'), ('dip_env_health', 'Diploma in Environmental Health'), ('dip_him', 'Diploma in Health Information Management'), ('dip_xray', 'Diploma in X-Ray and Imaging Technology'), ('dip_nutrition', 'Diploma in Nutrition and Dietetics'), ('cert_jchew', 'Certificate in Community Health (JCHEW)'), ('retraining_jchew', 'Retraining Programme in Community Health'), ('dip_pharmacy', 'Diploma in Pharmacy Technology')], max_length=50),
        ),
    ]
