# Generated by Django 4.2.7 on 2026-06-22 06:20

from django.db import migrations


def seed_programmes(apps, schema_editor):
    Programme = apps.get_model('portal', 'Programme')
    programmes = [
        {
            'name': 'National Diploma in Community Health (ND CHEW)',
            'code': 'ND-CHEW',
            'category': 'nd',
            'duration': '3 Years',
            'description': 'Comprehensive national diploma programme training Community Health Extension Workers for primary healthcare delivery.',
            'accreditation_body': 'CHPRBN',
            'icon': 'fa-heartbeat',
            'order': 1,
        },
        {
            'name': 'Diploma in Environmental Health',
            'code': 'DIP-EH',
            'category': 'dip',
            'duration': '2 Years',
            'description': 'Diploma programme training Environmental Health Officers for sanitation, pollution control, and public health.',
            'accreditation_body': 'EHCON',
            'icon': 'fa-leaf',
            'order': 2,
        },
        {
            'name': 'Diploma in Health Information Management',
            'code': 'DIP-HIM',
            'category': 'dip',
            'duration': '2 Years',
            'description': 'Diploma in health records management, health informatics, and medical coding for healthcare facilities.',
            'accreditation_body': 'WAHEB',
            'icon': 'fa-notes-medical',
            'order': 3,
        },
        {
            'name': 'Diploma in X-Ray and Imaging Technology',
            'code': 'DIP-XRAY',
            'category': 'dip',
            'duration': '2 Years',
            'description': 'Diploma in diagnostic radiography, medical imaging, and radiological technology.',
            'accreditation_body': 'WAHEB',
            'icon': 'fa-x-ray',
            'order': 4,
        },
        {
            'name': 'Diploma in Nutrition and Dietetics',
            'code': 'DIP-NUTR',
            'category': 'dip',
            'duration': '2 Years',
            'description': 'Diploma in food science, clinical nutrition, and dietary management for health promotion.',
            'accreditation_body': 'WAHEB',
            'icon': 'fa-apple-alt',
            'order': 5,
        },
        {
            'name': 'Certificate in Community Health (JCHEW)',
            'code': 'CERT-JCHEW',
            'category': 'cert',
            'duration': '2 Years',
            'description': 'Junior Community Health Extension Worker programme for foundational community health practice.',
            'accreditation_body': 'CHPRBN',
            'icon': 'fa-certificate',
            'order': 6,
        },
        {
            'name': 'Retraining Programme in Community Health',
            'code': 'RETRAIN-CHEW',
            'category': 'retraining',
            'duration': '1 Year',
            'description': 'Advanced retraining programme for JCHEW certificate holders seeking career progression.',
            'accreditation_body': 'CHPRBN',
            'icon': 'fa-sync-alt',
            'order': 7,
        },
        {
            'name': 'Diploma in Pharmacy Technology',
            'code': 'DIP-PHARM',
            'category': 'dip',
            'duration': '2 Years',
            'description': 'Diploma in pharmacy technology training pharmaceutical technicians for hospital and community practice.',
            'accreditation_body': 'WAHEB',
            'icon': 'fa-prescription-bottle',
            'order': 8,
        },
    ]
    for data in programmes:
        Programme.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_programme_application_application_type_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_programmes),
    ]
