# Generated by Django 4.2.7 on 2026-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_update_programmes_chesf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_choice',
            field=models.CharField(blank=True, choices=[('nd_chew', 'National Diploma in Community Health (ND-CHEW)'), ('chew', 'Diploma in Community Health Extension Worker (CHEW)'), ('jchew', 'Junior Community Health Extension Workers (JCHEW)'), ('nd_env_health', 'National Diploma in Environmental Health (ND)'), ('hnd_env_health', 'Higher National Diploma in Environmental Health (HND)'), ('him', 'Diploma in Health Information Management (HIM)'), ('hpe', 'Diploma in Health Promotion & Education (HPE)'), ('dph', 'Diploma in Public Health (DPH)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('nd_chew', 'National Diploma in Community Health (ND-CHEW)'), ('chew', 'Diploma in Community Health Extension Worker (CHEW)'), ('jchew', 'Junior Community Health Extension Workers (JCHEW)'), ('nd_env_health', 'National Diploma in Environmental Health (ND)'), ('hnd_env_health', 'Higher National Diploma in Environmental Health (HND)'), ('him', 'Diploma in Health Information Management (HIM)'), ('hpe', 'Diploma in Health Promotion & Education (HPE)'), ('dph', 'Diploma in Public Health (DPH)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.CharField(choices=[('nd', 'National Diploma'), ('dip', 'Diploma'), ('cert', 'Certificate'), ('hnd', 'Higher National Diploma'), ('retraining', 'Retraining')], default='dip', max_length=20),
        ),
    ]
